<?php 
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Invoice extends Model 
{
	

	/**
     * The table associated with the model.
     *
     * @var string
     */
	protected $table = 'dbo.invoice';
	

	/**
     * The table primary key field
     *
     * @var string
     */
	protected $primaryKey = 'ordnumunit';
	public $incrementing = false;
	

	/**
     * Table fillable fields
     *
     * @var array
     */
	protected $fillable = ["regisno","invtype","invnum","referenceno","transcode","refinvno","refdate","duedate","trantype","trannum","ordnum","ordnumunit","refordnum","cashier","shiftno","empcode","empname","personcode","peronname","custcode","custname","areacode","acctcode","acctname","baseacct","chartcode","gross","grossamt","netamount","discamount","amount","totalcost","grossorder","netorder","vatorder","discorder","orderamt","ordercost","payment","balance","addpercent","discone","disctwo","discthree","discfour","terms","withvat","vatamt","discountrate","discount","gltype","refnum","ifvoid","ifreserved","finishdate","posbalance","checks","nochecks","giftcheck","card","cash","nonmonetary","credit","changeamt","payaccepted","cashsale","packnum","released","invserved","forrelease","invwith","refdr","store","bodega","warecode","forpickup","approved","remarks","deliverycharge","rrnum","rrtran","invname","netofvat","scdiscount","amountdue","addvat","tamountdue","vatable","vatex","zerorated","invoicetype","salestype","withdr","status","division","taxtype","transtype","checkno","checkdate","checkbank","runningbalance","glhid","paytype","transactionno","transactiondate","ponumber","statementno","statementfrom","statementto","speriod","datepaid","datepaid2","datepaid3","ewtax","netofewtax","cmnumber","iscancel","accountsgroup","bwtax","txtype","withewtax","withbwtax","assignment","localcurrency","doccurrency","shipmentno","particulars","taxdue"];
	

	/**
     * Set search query for the model
	 * @param \Illuminate\Database\Eloquent\Builder $query
	 * @param string $text
     */
	public static function search($query, $text){
		//search table record 
		$search_condition = '(
				ASSIGNMENT LIKE ?  OR 
				SHIPMENTNO LIKE ?  OR 
				PARTICULARS LIKE ? 
		)';
		$search_params = [
			"%$text%","%$text%","%$text%"
		];
		//setting search conditions
		$query->whereRaw($search_condition, $search_params);
	}
	

	/**
     * return list page fields of the model.
     * 
     * @return array
     */
	public static function listFields(){
		return [ 
			"REGISNO AS regisno", 
			"INVTYPE AS invtype", 
			"INVNUM AS invnum", 
			"REFERENCENO AS referenceno", 
			"TRANSCODE AS transcode", 
			"REFINVNO AS refinvno", 
			"REFDATE AS refdate", 
			"DUEDATE AS duedate", 
			"TRANTYPE AS trantype", 
			"TRANNUM AS trannum", 
			"ORDNUM AS ordnum", 
			"ORDNUMUNIT AS ordnumunit", 
			"REFORDNUM AS refordnum", 
			"CASHIER AS cashier", 
			"SHIFTNO AS shiftno", 
			"EMPCODE AS empcode", 
			"EMPNAME AS empname", 
			"PERSONCODE AS personcode", 
			"PERONNAME AS peronname", 
			"CUSTCODE AS custcode", 
			"CUSTNAME AS custname", 
			"AREACODE AS areacode", 
			"ACCTCODE AS acctcode", 
			"ACCTNAME AS acctname", 
			"BASEACCT AS baseacct", 
			"CHARTCODE AS chartcode", 
			"GROSS AS gross", 
			"GROSSAMT AS grossamt", 
			"NETAMOUNT AS netamount", 
			"DISCAMOUNT AS discamount", 
			"AMOUNT AS amount", 
			"TOTALCOST AS totalcost", 
			"GROSSORDER AS grossorder", 
			"NETORDER AS netorder", 
			"VATORDER AS vatorder", 
			"DISCORDER AS discorder", 
			"ORDERAMT AS orderamt", 
			"ORDERCOST AS ordercost", 
			"PAYMENT AS payment", 
			"BALANCE AS balance", 
			"ADDPERCENT AS addpercent", 
			"DISCONE AS discone", 
			"DISCTWO AS disctwo", 
			"DISCTHREE AS discthree", 
			"DISCFOUR AS discfour", 
			"TERMS AS terms", 
			"WITHVAT AS withvat", 
			"VATAMT AS vatamt", 
			"DISCOUNTRATE AS discountrate", 
			"DISCOUNT AS discount", 
			"GLTYPE AS gltype", 
			"REFNUM AS refnum", 
			"IFVOID AS ifvoid", 
			"IFRESERVED AS ifreserved", 
			"FINISHDATE AS finishdate", 
			"POSBALANCE AS posbalance", 
			"Checks AS checks", 
			"NOCHECKS AS nochecks", 
			"GIFTCHECK AS giftcheck", 
			"CARD AS card", 
			"CASH AS cash", 
			"NONMONETARY AS nonmonetary", 
			"CREDIT AS credit", 
			"CHANGEAMT AS changeamt", 
			"PAYACCEPTED AS payaccepted", 
			"CASHSALE AS cashsale", 
			"PACKNUM AS packnum", 
			"RELEASED AS released", 
			"INVSERVED AS invserved", 
			"FORRELEASE AS forrelease", 
			"INVWITH AS invwith", 
			"REFDR AS refdr", 
			"STORE AS store", 
			"BODEGA AS bodega", 
			"WARECODE AS warecode", 
			"FORPICKUP AS forpickup", 
			"APPROVED AS approved", 
			"REMARKS AS remarks", 
			"DELIVERYCHARGE AS deliverycharge", 
			"RRNUM AS rrnum", 
			"RRTRAN AS rrtran", 
			"INVNAME AS invname", 
			"NETOFVAT AS netofvat", 
			"SCDISCOUNT AS scdiscount", 
			"AMOUNTDUE AS amountdue", 
			"ADDVAT AS addvat", 
			"TAMOUNTDUE AS tamountdue", 
			"VATABLE AS vatable", 
			"VATEX AS vatex", 
			"ZERORATED AS zerorated", 
			"INVOICETYPE AS invoicetype", 
			"SALESTYPE AS salestype", 
			"WITHDR AS withdr", 
			"STATUS AS status", 
			"DIVISION AS division", 
			"TAXTYPE AS taxtype", 
			"TRANSTYPE AS transtype", 
			"CHECKNO AS checkno", 
			"CHECKDATE AS checkdate", 
			"CHECKBANK AS checkbank", 
			"RUNNINGBALANCE AS runningbalance", 
			"GLHID AS glhid", 
			"PAYTYPE AS paytype", 
			"TRANSACTIONNO AS transactionno", 
			"TRANSACTIONDATE AS transactiondate", 
			"PONUMBER AS ponumber", 
			"STATEMENTNO AS statementno", 
			"STATEMENTFROM AS statementfrom", 
			"STATEMENTTO AS statementto", 
			"SPERIOD AS speriod", 
			"DATEPAID AS datepaid", 
			"DATEPAID2 AS datepaid2", 
			"DATEPAID3 AS datepaid3", 
			"EWTAX AS ewtax", 
			"NETOFEWTAX AS netofewtax", 
			"CMNUMBER AS cmnumber", 
			"ISCANCEL AS iscancel", 
			"ACCOUNTSGROUP AS accountsgroup", 
			"BWTAX AS bwtax", 
			"TXTYPE AS txtype", 
			"WITHEWTAX AS withewtax", 
			"WITHBWTAX AS withbwtax", 
			"ASSIGNMENT AS assignment", 
			"LOCALCURRENCY AS localcurrency", 
			"DOCCURRENCY AS doccurrency", 
			"SHIPMENTNO AS shipmentno", 
			"PARTICULARS AS particulars", 
			"TAXDUE AS taxdue" 
		];
	}
	

	/**
     * return exportList page fields of the model.
     * 
     * @return array
     */
	public static function exportListFields(){
		return [ 
			"REGISNO AS regisno", 
			"INVTYPE AS invtype", 
			"INVNUM AS invnum", 
			"REFERENCENO AS referenceno", 
			"TRANSCODE AS transcode", 
			"REFINVNO AS refinvno", 
			"REFDATE AS refdate", 
			"DUEDATE AS duedate", 
			"TRANTYPE AS trantype", 
			"TRANNUM AS trannum", 
			"ORDNUM AS ordnum", 
			"ORDNUMUNIT AS ordnumunit", 
			"REFORDNUM AS refordnum", 
			"CASHIER AS cashier", 
			"SHIFTNO AS shiftno", 
			"EMPCODE AS empcode", 
			"EMPNAME AS empname", 
			"PERSONCODE AS personcode", 
			"PERONNAME AS peronname", 
			"CUSTCODE AS custcode", 
			"CUSTNAME AS custname", 
			"AREACODE AS areacode", 
			"ACCTCODE AS acctcode", 
			"ACCTNAME AS acctname", 
			"BASEACCT AS baseacct", 
			"CHARTCODE AS chartcode", 
			"GROSS AS gross", 
			"GROSSAMT AS grossamt", 
			"NETAMOUNT AS netamount", 
			"DISCAMOUNT AS discamount", 
			"AMOUNT AS amount", 
			"TOTALCOST AS totalcost", 
			"GROSSORDER AS grossorder", 
			"NETORDER AS netorder", 
			"VATORDER AS vatorder", 
			"DISCORDER AS discorder", 
			"ORDERAMT AS orderamt", 
			"ORDERCOST AS ordercost", 
			"PAYMENT AS payment", 
			"BALANCE AS balance", 
			"ADDPERCENT AS addpercent", 
			"DISCONE AS discone", 
			"DISCTWO AS disctwo", 
			"DISCTHREE AS discthree", 
			"DISCFOUR AS discfour", 
			"TERMS AS terms", 
			"WITHVAT AS withvat", 
			"VATAMT AS vatamt", 
			"DISCOUNTRATE AS discountrate", 
			"DISCOUNT AS discount", 
			"GLTYPE AS gltype", 
			"REFNUM AS refnum", 
			"IFVOID AS ifvoid", 
			"IFRESERVED AS ifreserved", 
			"FINISHDATE AS finishdate", 
			"POSBALANCE AS posbalance", 
			"Checks AS checks", 
			"NOCHECKS AS nochecks", 
			"GIFTCHECK AS giftcheck", 
			"CARD AS card", 
			"CASH AS cash", 
			"NONMONETARY AS nonmonetary", 
			"CREDIT AS credit", 
			"CHANGEAMT AS changeamt", 
			"PAYACCEPTED AS payaccepted", 
			"CASHSALE AS cashsale", 
			"PACKNUM AS packnum", 
			"RELEASED AS released", 
			"INVSERVED AS invserved", 
			"FORRELEASE AS forrelease", 
			"INVWITH AS invwith", 
			"REFDR AS refdr", 
			"STORE AS store", 
			"BODEGA AS bodega", 
			"WARECODE AS warecode", 
			"FORPICKUP AS forpickup", 
			"APPROVED AS approved", 
			"REMARKS AS remarks", 
			"DELIVERYCHARGE AS deliverycharge", 
			"RRNUM AS rrnum", 
			"RRTRAN AS rrtran", 
			"INVNAME AS invname", 
			"NETOFVAT AS netofvat", 
			"SCDISCOUNT AS scdiscount", 
			"AMOUNTDUE AS amountdue", 
			"ADDVAT AS addvat", 
			"TAMOUNTDUE AS tamountdue", 
			"VATABLE AS vatable", 
			"VATEX AS vatex", 
			"ZERORATED AS zerorated", 
			"INVOICETYPE AS invoicetype", 
			"SALESTYPE AS salestype", 
			"WITHDR AS withdr", 
			"STATUS AS status", 
			"DIVISION AS division", 
			"TAXTYPE AS taxtype", 
			"TRANSTYPE AS transtype", 
			"CHECKNO AS checkno", 
			"CHECKDATE AS checkdate", 
			"CHECKBANK AS checkbank", 
			"RUNNINGBALANCE AS runningbalance", 
			"GLHID AS glhid", 
			"PAYTYPE AS paytype", 
			"TRANSACTIONNO AS transactionno", 
			"TRANSACTIONDATE AS transactiondate", 
			"PONUMBER AS ponumber", 
			"STATEMENTNO AS statementno", 
			"STATEMENTFROM AS statementfrom", 
			"STATEMENTTO AS statementto", 
			"SPERIOD AS speriod", 
			"DATEPAID AS datepaid", 
			"DATEPAID2 AS datepaid2", 
			"DATEPAID3 AS datepaid3", 
			"EWTAX AS ewtax", 
			"NETOFEWTAX AS netofewtax", 
			"CMNUMBER AS cmnumber", 
			"ISCANCEL AS iscancel", 
			"ACCOUNTSGROUP AS accountsgroup", 
			"BWTAX AS bwtax", 
			"TXTYPE AS txtype", 
			"WITHEWTAX AS withewtax", 
			"WITHBWTAX AS withbwtax", 
			"ASSIGNMENT AS assignment", 
			"LOCALCURRENCY AS localcurrency", 
			"DOCCURRENCY AS doccurrency", 
			"SHIPMENTNO AS shipmentno", 
			"PARTICULARS AS particulars", 
			"TAXDUE AS taxdue" 
		];
	}
	

	/**
     * return view page fields of the model.
     * 
     * @return array
     */
	public static function viewFields(){
		return [ 
			"REGISNO AS regisno", 
			"INVTYPE AS invtype", 
			"INVNUM AS invnum", 
			"REFERENCENO AS referenceno", 
			"TRANSCODE AS transcode", 
			"REFINVNO AS refinvno", 
			"REFDATE AS refdate", 
			"DUEDATE AS duedate", 
			"TRANTYPE AS trantype", 
			"TRANNUM AS trannum", 
			"ORDNUM AS ordnum", 
			"ORDNUMUNIT AS ordnumunit", 
			"REFORDNUM AS refordnum", 
			"CASHIER AS cashier", 
			"SHIFTNO AS shiftno", 
			"EMPCODE AS empcode", 
			"EMPNAME AS empname", 
			"PERSONCODE AS personcode", 
			"PERONNAME AS peronname", 
			"CUSTCODE AS custcode", 
			"CUSTNAME AS custname", 
			"AREACODE AS areacode", 
			"ACCTCODE AS acctcode", 
			"ACCTNAME AS acctname", 
			"BASEACCT AS baseacct", 
			"CHARTCODE AS chartcode", 
			"GROSS AS gross", 
			"GROSSAMT AS grossamt", 
			"NETAMOUNT AS netamount", 
			"DISCAMOUNT AS discamount", 
			"AMOUNT AS amount", 
			"TOTALCOST AS totalcost", 
			"GROSSORDER AS grossorder", 
			"NETORDER AS netorder", 
			"VATORDER AS vatorder", 
			"DISCORDER AS discorder", 
			"ORDERAMT AS orderamt", 
			"ORDERCOST AS ordercost", 
			"PAYMENT AS payment", 
			"BALANCE AS balance", 
			"ADDPERCENT AS addpercent", 
			"DISCONE AS discone", 
			"DISCTWO AS disctwo", 
			"DISCTHREE AS discthree", 
			"DISCFOUR AS discfour", 
			"TERMS AS terms", 
			"WITHVAT AS withvat", 
			"VATAMT AS vatamt", 
			"DISCOUNTRATE AS discountrate", 
			"DISCOUNT AS discount", 
			"GLTYPE AS gltype", 
			"REFNUM AS refnum", 
			"IFVOID AS ifvoid", 
			"IFRESERVED AS ifreserved", 
			"FINISHDATE AS finishdate", 
			"POSBALANCE AS posbalance", 
			"Checks AS checks", 
			"NOCHECKS AS nochecks", 
			"GIFTCHECK AS giftcheck", 
			"CARD AS card", 
			"CASH AS cash", 
			"NONMONETARY AS nonmonetary", 
			"CREDIT AS credit", 
			"CHANGEAMT AS changeamt", 
			"PAYACCEPTED AS payaccepted", 
			"CASHSALE AS cashsale", 
			"PACKNUM AS packnum", 
			"RELEASED AS released", 
			"INVSERVED AS invserved", 
			"FORRELEASE AS forrelease", 
			"INVWITH AS invwith", 
			"REFDR AS refdr", 
			"STORE AS store", 
			"BODEGA AS bodega", 
			"WARECODE AS warecode", 
			"FORPICKUP AS forpickup", 
			"APPROVED AS approved", 
			"REMARKS AS remarks", 
			"DELIVERYCHARGE AS deliverycharge", 
			"RRNUM AS rrnum", 
			"RRTRAN AS rrtran", 
			"INVNAME AS invname", 
			"NETOFVAT AS netofvat", 
			"SCDISCOUNT AS scdiscount", 
			"AMOUNTDUE AS amountdue", 
			"ADDVAT AS addvat", 
			"TAMOUNTDUE AS tamountdue", 
			"VATABLE AS vatable", 
			"VATEX AS vatex", 
			"ZERORATED AS zerorated", 
			"INVOICETYPE AS invoicetype", 
			"SALESTYPE AS salestype", 
			"WITHDR AS withdr", 
			"STATUS AS status", 
			"DIVISION AS division", 
			"TAXTYPE AS taxtype", 
			"TRANSTYPE AS transtype", 
			"CHECKNO AS checkno", 
			"CHECKDATE AS checkdate", 
			"CHECKBANK AS checkbank", 
			"RUNNINGBALANCE AS runningbalance", 
			"GLHID AS glhid", 
			"PAYTYPE AS paytype", 
			"TRANSACTIONNO AS transactionno", 
			"TRANSACTIONDATE AS transactiondate", 
			"PONUMBER AS ponumber", 
			"STATEMENTNO AS statementno", 
			"STATEMENTFROM AS statementfrom", 
			"STATEMENTTO AS statementto", 
			"SPERIOD AS speriod", 
			"DATEPAID AS datepaid", 
			"DATEPAID2 AS datepaid2", 
			"DATEPAID3 AS datepaid3", 
			"EWTAX AS ewtax", 
			"NETOFEWTAX AS netofewtax", 
			"CMNUMBER AS cmnumber", 
			"ISCANCEL AS iscancel", 
			"ACCOUNTSGROUP AS accountsgroup", 
			"BWTAX AS bwtax", 
			"TXTYPE AS txtype", 
			"WITHEWTAX AS withewtax", 
			"WITHBWTAX AS withbwtax", 
			"ASSIGNMENT AS assignment", 
			"LOCALCURRENCY AS localcurrency", 
			"DOCCURRENCY AS doccurrency", 
			"SHIPMENTNO AS shipmentno", 
			"PARTICULARS AS particulars", 
			"TAXDUE AS taxdue" 
		];
	}
	

	/**
     * return exportView page fields of the model.
     * 
     * @return array
     */
	public static function exportViewFields(){
		return [ 
			"REGISNO AS regisno", 
			"INVTYPE AS invtype", 
			"INVNUM AS invnum", 
			"REFERENCENO AS referenceno", 
			"TRANSCODE AS transcode", 
			"REFINVNO AS refinvno", 
			"REFDATE AS refdate", 
			"DUEDATE AS duedate", 
			"TRANTYPE AS trantype", 
			"TRANNUM AS trannum", 
			"ORDNUM AS ordnum", 
			"ORDNUMUNIT AS ordnumunit", 
			"REFORDNUM AS refordnum", 
			"CASHIER AS cashier", 
			"SHIFTNO AS shiftno", 
			"EMPCODE AS empcode", 
			"EMPNAME AS empname", 
			"PERSONCODE AS personcode", 
			"PERONNAME AS peronname", 
			"CUSTCODE AS custcode", 
			"CUSTNAME AS custname", 
			"AREACODE AS areacode", 
			"ACCTCODE AS acctcode", 
			"ACCTNAME AS acctname", 
			"BASEACCT AS baseacct", 
			"CHARTCODE AS chartcode", 
			"GROSS AS gross", 
			"GROSSAMT AS grossamt", 
			"NETAMOUNT AS netamount", 
			"DISCAMOUNT AS discamount", 
			"AMOUNT AS amount", 
			"TOTALCOST AS totalcost", 
			"GROSSORDER AS grossorder", 
			"NETORDER AS netorder", 
			"VATORDER AS vatorder", 
			"DISCORDER AS discorder", 
			"ORDERAMT AS orderamt", 
			"ORDERCOST AS ordercost", 
			"PAYMENT AS payment", 
			"BALANCE AS balance", 
			"ADDPERCENT AS addpercent", 
			"DISCONE AS discone", 
			"DISCTWO AS disctwo", 
			"DISCTHREE AS discthree", 
			"DISCFOUR AS discfour", 
			"TERMS AS terms", 
			"WITHVAT AS withvat", 
			"VATAMT AS vatamt", 
			"DISCOUNTRATE AS discountrate", 
			"DISCOUNT AS discount", 
			"GLTYPE AS gltype", 
			"REFNUM AS refnum", 
			"IFVOID AS ifvoid", 
			"IFRESERVED AS ifreserved", 
			"FINISHDATE AS finishdate", 
			"POSBALANCE AS posbalance", 
			"Checks AS checks", 
			"NOCHECKS AS nochecks", 
			"GIFTCHECK AS giftcheck", 
			"CARD AS card", 
			"CASH AS cash", 
			"NONMONETARY AS nonmonetary", 
			"CREDIT AS credit", 
			"CHANGEAMT AS changeamt", 
			"PAYACCEPTED AS payaccepted", 
			"CASHSALE AS cashsale", 
			"PACKNUM AS packnum", 
			"RELEASED AS released", 
			"INVSERVED AS invserved", 
			"FORRELEASE AS forrelease", 
			"INVWITH AS invwith", 
			"REFDR AS refdr", 
			"STORE AS store", 
			"BODEGA AS bodega", 
			"WARECODE AS warecode", 
			"FORPICKUP AS forpickup", 
			"APPROVED AS approved", 
			"REMARKS AS remarks", 
			"DELIVERYCHARGE AS deliverycharge", 
			"RRNUM AS rrnum", 
			"RRTRAN AS rrtran", 
			"INVNAME AS invname", 
			"NETOFVAT AS netofvat", 
			"SCDISCOUNT AS scdiscount", 
			"AMOUNTDUE AS amountdue", 
			"ADDVAT AS addvat", 
			"TAMOUNTDUE AS tamountdue", 
			"VATABLE AS vatable", 
			"VATEX AS vatex", 
			"ZERORATED AS zerorated", 
			"INVOICETYPE AS invoicetype", 
			"SALESTYPE AS salestype", 
			"WITHDR AS withdr", 
			"STATUS AS status", 
			"DIVISION AS division", 
			"TAXTYPE AS taxtype", 
			"TRANSTYPE AS transtype", 
			"CHECKNO AS checkno", 
			"CHECKDATE AS checkdate", 
			"CHECKBANK AS checkbank", 
			"RUNNINGBALANCE AS runningbalance", 
			"GLHID AS glhid", 
			"PAYTYPE AS paytype", 
			"TRANSACTIONNO AS transactionno", 
			"TRANSACTIONDATE AS transactiondate", 
			"PONUMBER AS ponumber", 
			"STATEMENTNO AS statementno", 
			"STATEMENTFROM AS statementfrom", 
			"STATEMENTTO AS statementto", 
			"SPERIOD AS speriod", 
			"DATEPAID AS datepaid", 
			"DATEPAID2 AS datepaid2", 
			"DATEPAID3 AS datepaid3", 
			"EWTAX AS ewtax", 
			"NETOFEWTAX AS netofewtax", 
			"CMNUMBER AS cmnumber", 
			"ISCANCEL AS iscancel", 
			"ACCOUNTSGROUP AS accountsgroup", 
			"BWTAX AS bwtax", 
			"TXTYPE AS txtype", 
			"WITHEWTAX AS withewtax", 
			"WITHBWTAX AS withbwtax", 
			"ASSIGNMENT AS assignment", 
			"LOCALCURRENCY AS localcurrency", 
			"DOCCURRENCY AS doccurrency", 
			"SHIPMENTNO AS shipmentno", 
			"PARTICULARS AS particulars", 
			"TAXDUE AS taxdue" 
		];
	}
	

	/**
     * return edit page fields of the model.
     * 
     * @return array
     */
	public static function editFields(){
		return [ 
			"REGISNO AS regisno", 
			"INVTYPE AS invtype", 
			"INVNUM AS invnum", 
			"REFERENCENO AS referenceno", 
			"TRANSCODE AS transcode", 
			"REFINVNO AS refinvno", 
			"REFDATE AS refdate", 
			"DUEDATE AS duedate", 
			"TRANTYPE AS trantype", 
			"TRANNUM AS trannum", 
			"ORDNUM AS ordnum", 
			"ORDNUMUNIT AS ordnumunit", 
			"REFORDNUM AS refordnum", 
			"CASHIER AS cashier", 
			"SHIFTNO AS shiftno", 
			"EMPCODE AS empcode", 
			"EMPNAME AS empname", 
			"PERSONCODE AS personcode", 
			"PERONNAME AS peronname", 
			"CUSTCODE AS custcode", 
			"CUSTNAME AS custname", 
			"AREACODE AS areacode", 
			"ACCTCODE AS acctcode", 
			"ACCTNAME AS acctname", 
			"BASEACCT AS baseacct", 
			"CHARTCODE AS chartcode", 
			"GROSS AS gross", 
			"GROSSAMT AS grossamt", 
			"NETAMOUNT AS netamount", 
			"DISCAMOUNT AS discamount", 
			"AMOUNT AS amount", 
			"TOTALCOST AS totalcost", 
			"GROSSORDER AS grossorder", 
			"NETORDER AS netorder", 
			"VATORDER AS vatorder", 
			"DISCORDER AS discorder", 
			"ORDERAMT AS orderamt", 
			"ORDERCOST AS ordercost", 
			"PAYMENT AS payment", 
			"BALANCE AS balance", 
			"ADDPERCENT AS addpercent", 
			"DISCONE AS discone", 
			"DISCTWO AS disctwo", 
			"DISCTHREE AS discthree", 
			"DISCFOUR AS discfour", 
			"TERMS AS terms", 
			"WITHVAT AS withvat", 
			"VATAMT AS vatamt", 
			"DISCOUNTRATE AS discountrate", 
			"DISCOUNT AS discount", 
			"GLTYPE AS gltype", 
			"REFNUM AS refnum", 
			"IFVOID AS ifvoid", 
			"IFRESERVED AS ifreserved", 
			"FINISHDATE AS finishdate", 
			"POSBALANCE AS posbalance", 
			"Checks AS checks", 
			"NOCHECKS AS nochecks", 
			"GIFTCHECK AS giftcheck", 
			"CARD AS card", 
			"CASH AS cash", 
			"NONMONETARY AS nonmonetary", 
			"CREDIT AS credit", 
			"CHANGEAMT AS changeamt", 
			"PAYACCEPTED AS payaccepted", 
			"CASHSALE AS cashsale", 
			"PACKNUM AS packnum", 
			"RELEASED AS released", 
			"INVSERVED AS invserved", 
			"FORRELEASE AS forrelease", 
			"INVWITH AS invwith", 
			"REFDR AS refdr", 
			"STORE AS store", 
			"BODEGA AS bodega", 
			"WARECODE AS warecode", 
			"FORPICKUP AS forpickup", 
			"APPROVED AS approved", 
			"REMARKS AS remarks", 
			"DELIVERYCHARGE AS deliverycharge", 
			"RRNUM AS rrnum", 
			"RRTRAN AS rrtran", 
			"INVNAME AS invname", 
			"NETOFVAT AS netofvat", 
			"SCDISCOUNT AS scdiscount", 
			"AMOUNTDUE AS amountdue", 
			"ADDVAT AS addvat", 
			"TAMOUNTDUE AS tamountdue", 
			"VATABLE AS vatable", 
			"VATEX AS vatex", 
			"ZERORATED AS zerorated", 
			"INVOICETYPE AS invoicetype", 
			"SALESTYPE AS salestype", 
			"WITHDR AS withdr", 
			"STATUS AS status", 
			"DIVISION AS division", 
			"TAXTYPE AS taxtype", 
			"TRANSTYPE AS transtype", 
			"CHECKNO AS checkno", 
			"CHECKDATE AS checkdate", 
			"CHECKBANK AS checkbank", 
			"RUNNINGBALANCE AS runningbalance", 
			"GLHID AS glhid", 
			"PAYTYPE AS paytype", 
			"TRANSACTIONNO AS transactionno", 
			"TRANSACTIONDATE AS transactiondate", 
			"PONUMBER AS ponumber", 
			"STATEMENTNO AS statementno", 
			"STATEMENTFROM AS statementfrom", 
			"STATEMENTTO AS statementto", 
			"SPERIOD AS speriod", 
			"DATEPAID AS datepaid", 
			"DATEPAID2 AS datepaid2", 
			"DATEPAID3 AS datepaid3", 
			"EWTAX AS ewtax", 
			"NETOFEWTAX AS netofewtax", 
			"CMNUMBER AS cmnumber", 
			"ISCANCEL AS iscancel", 
			"ACCOUNTSGROUP AS accountsgroup", 
			"BWTAX AS bwtax", 
			"TXTYPE AS txtype", 
			"WITHEWTAX AS withewtax", 
			"WITHBWTAX AS withbwtax", 
			"ASSIGNMENT AS assignment", 
			"LOCALCURRENCY AS localcurrency", 
			"DOCCURRENCY AS doccurrency", 
			"SHIPMENTNO AS shipmentno", 
			"PARTICULARS AS particulars", 
			"TAXDUE AS taxdue" 
		];
	}
	

	/**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
	public $timestamps = false;
}
